### ISSUE TITLE
 fatal error: vspm_public.h: No such file or directory

### ISSUE THREAD

**Issue by mistyron** [MistySOM/rzv2l#18]
This is for record keeping only, e-con entered the following support request:

We have started to bring up our camera with Mistywest V2L carrier board. In which we are facing build error as shown below,

/home/yocto/rzv_vlp_v3.0.0/build/tmp/work/smarc_rzv2l-poky-linux/kernel-module-vspmif/1.0-r0/git/vspm_if-module/files/vspm_if/drv/vspm_if_main.c:69:10: fatal error: vspm_public.h: No such file or directory
 #include "vspm_public.h"
          ^~~~~~~~~~~~~~~
compilation terminated.

Also, kindly please share below details,

    * Carrier board camera connector details - Rev A
    * Known issues if there any. eg. like SD card issue as seen in G2L carrier.

**Comment by mistyron** [comment]
Romn replied:
Hi Elango,


Oh, interersting. You need to help me to help you. When or where do you experience this? I need some background information about the environment that you're working in so that I can duplicate it.


Thanks,

Ron

**Comment by mistyron** [comment]
e-con replied:
 Hi Ron,

We Just started to setup the basic build environment by following the below guidelines

https://github.com/MistySOM/wiki/blob/master/content/GettingStarted.md

We are facing yocto build issue after invoking the docker with below commands  (just setting up the basic environment , we didn't port our driver still).

$ ./run.sh -c <path to local cache dir>

Thanks,
Elango Palanisamy

**Comment by mistyron** [comment]
Ron replied:
Hi Elango,


To follow up on your request regarding:
 fatal error: vspm_public.h: No such file or directory
I tried to duplicate it but was not able to.
May I suggest the following:

    Check out and try to build the latest from the master branch at [mailto:git@github.com:MistySOM/rzv2l.git]git@github.com:MistySOM/rzv2l.git ([MistySOM/rzv2l: MH11-V2L-1 (github.com)](https://github.com/MistySOM/rzv2l/)). $ git clone [mailto:git@github.com:MistySOM/rzv2l.git]git@github.com:MistySOM/rzv2l.git
        if you already have a cloned copy you can also do:
            $ git checkout master
            $ git pull
    $ cd Build
    $ ./build.sh
    $ ./run.sh -c /your/cache/dir

if this doesn't help, you cabn try to run the container in the dev-shell mode:

    Check out and try to build the latest from the master branch at [mailto:git@github.com:MistySOM/rzv2l.git]git@github.com:MistySOM/rzv2l.git ([MistySOM/rzv2l: MH11-V2L-1 (github.com)](https://github.com/MistySOM/rzv2l/)). $ git clone [mailto:git@github.com:MistySOM/rzv2l.git]git@github.com:MistySOM/rzv2l.git
        if you already have a cloned copy you can also do:
            $ git checkout master
            $ git pull
    $ cd Build
    $ ./build.sh
    $ ./run.sh -c /your/cache/dir -n
        the container will start and give you a shell within it:
        cd rzv_vlp_v3.0.0/
        . poky//oe-init-build-env
        bitbake mistysom-image
        if it fails, it will give you a complete view of the failure, please copy and paste the complete screen so that I can see the complete context of the error.


I hope the above helps!

Thank you,

Ron

**Comment by mistyron** [comment]
e-con:

      Hi Ron,

     Thanks for the tremendous support.

     The issue got resolved. 

      Actually, the build system reported "/home/yocto/rzv_***/build/tmp is running low" and it stopped the build.       and during the rerun , it reported "vspm_public.h" missing error.

      when we mounted tmp directory outside container likewise sstate and downloads directory.
      the build went through successfully.


      Regards,
      Elango Palanisamy

**Comment by matinlotfali** [comment]
We had a similar issue ourselves where the `/var` and `/tmp` directories used to be in a smaller root partition.
We solved this by moving and mounting those two directories outside of the root partition for the docker to feel more relaxed.
Should we document this ?
Should we add the "mount tmp directory outside the container" to the `run.sh` ?

**Comment by mistyron** [comment]
it's worth it to document the error and work around for it, yes. I don't know if it appears often enough to add an option to run.sh, it's worth a consideration but for now, I  think documenting will do. What's your opinion about this?

**Comment by matinlotfali** [comment]
I suggest we add it to the `README.md` in this repo.

**Comment by mistyron** [comment]
@matinlotfali Please go ahead and add it, then.

**Comment by matinlotfali** [comment]
@mistyron  See here: https://github.com/MistySOM/rzg2l/pull/25
If it gets approved, I will add it to V2L as well.

**Comment by matinlotfali** [comment]
Yes it was merged in #19
